### ISSUE TITLE
Revise source code tree

### ISSUE THREAD

**Issue by cczhu** [mhvk/scintillometry#11]
The current file structure, with folders for individual task, is overelaborate.  It makes far more sense to have a structure like:

```
scintillometry/
	tasks/
		base.py
		channelize.py
		dedisperse.py <- dm.py contents go in here
		integrate.py
	fourier/
		base.py
		numpy.py
		pyfftw.py	

docs/
	tasks/
		index.rst <- covers all tasks
	fourier/
		index.rst
```

**Comment by cczhu** [comment]
Talking a bit with Nikhil, I realized it might make more sense to do something slightly different:

```
scintillometry/
	tasks/
		base.py
		channelize.py
		dedisperse.py
		integrate.py
	fourier/
		base.py
		numpy.py
		pyfftw.py
        tools/
                dm.py

docs/
	tasks/
		index.rst <- covers all tasks
	fourier/
		index.rst
        tools/
                index.rst <- covers all tools.
```

We can also move `fourier` into `tools`, which would cleanly divide tasks from the quantities and functions they call upon to operate.  `fourier` is special enough, though, that I'm also happy to keep it in the code root directory.

**Comment by mhvk** [comment]
I'm not sure there should even be a `tasks` module; I think the four `*.py` files can just be in `scintillometry`; if we ever find they become too big, they can become directories (and still remain the same module from the python perspective). In `docs`, that would still leave a `tasks.rst`.

**Comment by cczhu** [comment]
#17 solved this, so closing.
