### ISSUE TITLE
task.close() should have an option that does not close the underline task

### ISSUE THREAD

**Issue by luojing1211** [mhvk/scintillometry#127]
The current .close() setup closes the underline task. Could we add one option that it does not delete the underline tasks? For instance, I have several DM corrections takes the same one Dedispersion class as the initial, If I close one correction task, it will delete the initial Dedispersion class. We could have a flag to avoid it. Maybe I can just delete the correction task. But I am not sure if this is the best way to do it.

**Comment by mhvk** [comment]
I changed that some time ago: #105 (and see current implementation: https://github.com/mhvk/scintillometry/blob/master/scintillometry/base.py#L413). Is it still a problem?

**Comment by mhvk** [comment]
p.s. Clearly, I did forget to update the docstring...
