### ISSUE TITLE
Different dispersion delay constant

### ISSUE THREAD

**Issue by theXYZT** [mhvk/scintillometry#21]
It seems the dispersion delay constant used in this package is different from the one that has worked in the past for similar work.

In `dm.py` you define it as:
`dispersion_delay_constant = u.s / 2.41e-4 * u.MHz**2 * u.cm**3 / u.pc`

where 1/2.41e-4 is interpreted as the floating-point number: 4149.377593360996

whereas in my scripts, it has been set to:
`4149. * u.s * u.MHz**2 * u.cm**3 / u.pc`

which is definitely different. How would we go about figuring out which value is correct? Is there a way to confirm?

**Comment by mhvk** [comment]
Ah, now I see what you meant. The number in `scintillometry` is the correct one; the `4149` came from the pulsar handbook and I thought it was the standard, but it is not. Tempo2 uses `2.41e-4`; see https://github.com/aarchiba/tempo2/blob/master/tempo2.h#L75 (and https://github.com/nanograv/tempo/blob/master/src/arrtim.f#L619 and https://github.com/nanograv/PINT/blob/master/pint/models/dispersion_model.py#L20

We should convert everywhere, and change dispersion measures accordingly... (which may mean correcting DM in the proofs of the B1957 mode-changing paper...)

**Comment by mhvk** [comment]
I'm closing this, since the usage is correct here...
