### ISSUE TITLE
Return data in a ndarray subclass with a count attribute?

### ISSUE THREAD

**Issue by mhvk** [mhvk/scintillometry#37]
For folding, we need to return not just the folded data, but also how many samples go in. For this purpose, we perhaps should return a subclass of `ndarray` which holds a `count` attribute. This could be extended to all tasks and even to baseband (https://github.com/mhvk/baseband/issues/286) to take into account missing data or data removed by, e.g., RFI clipping.

It seems reasonable for this attribute not to propagate much, if at all, i.e., most operations would delete it.

**Comment by luojing1211** [comment]
Another good practise is to add the labels for each dimension.

**Comment by mhvk** [comment]
Indeed, some of the basic metadata might as well be stored on the array. Though I'm not sure it needs to duplicate what is on the class from which the data is read.

**Comment by luojing1211** [comment]
I am a fan of self-described object. The metadata should be sufficient for others to understand it.  But I agree that keeping a balance is necessary.

**Comment by mhvk** [comment]
That's called a `PSRFits` file... Anyway, right now, there wouldn't be that much more metadata. Possibly we'd indeed just describe the axes, so `frequency`, `sideband`, `polarization`, and `time` attributes, maybe the latter lazily evaluated (or `start_time` and `sample_rate`).

**Comment by mhvk** [comment]
Just as a reminder for when we seriously start to think about this: one tricky aspect with an `ndarray` subclass is that any operation on such data will by default return a new instance of the subclass, but obviously without a correct `count`, etc., attribute. So, we either would need to do work to ensure that we loose our subclass in operations, or work to ensure `count`, etc., remain correct.

**Comment by mhvk** [comment]
Initial implementation in #44.
