### ISSUE TITLE
Error When Using Fold Class

### ISSUE THREAD

**Issue by IMFardz** [mhvk/scintillometry#60]
Recently, I have attempted to use the new Scintillometry error, and it appears I have run into a bug. I have attached my files, but I will also describe the problem here:

Initially, the data is stored as baseband in a multi-threaded mark4 format. In total, each mark4 file has 8 threads with four frequency sub-bands and 2 polarizations. The four frequency bandwidths are [312.25 - 320.25, 320.25 - 328.25, 328.25 - 336.25, 336.26 - 344.25] MHz, and the polarizations are [R, L]. So for instance, in each mark4 file, the first thread is (freq1, R), the second thread is (freq1, L), the third thread is (freq2, R), and so forth. 

Initially, I run my file fold.py. In this file, I use the scintillometry reshape class to reshape the streamer as follows:

rh = Reshape(fh, (4, 2))

Then, I call a Fold class that I defined in scintillometry_reduction (different than your scintillometry fold class) in the line

WF = sr.Fold(rh, dispersion_measure, frequency, sideband, polyco_file, polarization, fullpol, nthreads)

In this class, the error is thrown after I use the line which calls the Fold class in Scintillometry:

integrator = integration.Fold(power, n_phase=1024, phase=psr_polyco, step=self.interval, average=False)

where self.interval is 4 second (using astropy units) and is the sub integration time, psr_polyco is a polyco I generated with tempo2 and power is calculated from the above lines.

Essentially, what occurs is Fold calls the superclass init method for Integration which calls the super class init method for BaseTaskBase which calls the super class init method for Base which calls the method _check_frequency which tries (and fails) to broadcast the frequency axis to the same shape as the sample shape of the data. My suspicion is that somewhere in the Fold class, the shape is miscalculated. I have attached the full error message in error.txt. For some reason, it tries to broadcast the frequency array to the shape (1,4,4). However, I am not sure where this number is coming from, as the sample shape of the reader is (4,2) and the shape of both the sideband and frequency arrays is (1, 4, 2). 

Thanks!

[error.txt](https://github.com/mhvk/scintillometry/files/2870957/error.txt)
[scintillometry_reduction.txt](https://github.com/mhvk/scintillometry/files/2870959/scintillometry_reduction.txt)
[fold.txt](https://github.com/mhvk/scintillometry/files/2870960/fold.txt)

**Comment by mhvk** [comment]
@IMFardz - sorry to hear things are not working! It is a bit hard for me to judge what could be going wrong (I'm in India currently). Ideally, you would make a more minimal example that shows the problem. To make this self-contained, you could use the fake data generators.

But perhaps the first thing to do is, in `ipython`, once you have hit the error, do `%debug` and inspect what the various shapes are. Clearly, something is miscalculated, but it would be good to narrow down *where* that happens.

**Comment by mhvk** [comment]
OK, the more minimal example is:
```
import numpy as np
from astropy import units as u
from astropy.time import Time
from scintillometry import generators, shaping, integration, functions, dispersion, channelize

frequency = np.array([[320.25, 320.25], [320.25, 320.25], [336.25, 336.25], [336.25, 336.25]]) * u.MHz
sideband = np.array([[-1, -1], [1, 1], [-1, -1], [1, 1]])
polarization = ['R','L']

fh = generators.EmptyStreamGenerator((10000, 8), sample_rate=1.*u.Hz, start_time=Time('2018-01-01'),
                                     frequency=frequency.ravel(), sideband=sideband.ravel())
rh = shaping.Reshape(fh, (4, 2))
dh = dispersion.Dedisperse(rh, 0., frequency=frequency, sideband=sideband, samples_per_frame=100)
ch = channelize.Channelize(dh, 1)
ph = functions.Power(ch, polarization=polarization)
ih = integration.Fold(ph, n_phase=100, phase=lambda t: t, step=4*u.s)
```
Note that using `Square` instead of `Power` works...

**Comment by mhvk** [comment]
Hmm, I think the problem is that `Power` should check that the frequencies for the two polarizations are the same, and then remove those. And, arguably, `Channelize`, shouldn't produce a shape `(4, 2)` one.
So, a more minimal example:
```
import numpy as np
from astropy import units as u
from astropy.time import Time
from scintillometry import generators, integration, functions

frequency = np.array([[320.25], [320.25], [336.25], [336.25]]) * u.MHz
sideband = np.array([-1, -1])
polarization = ['R', 'L']

fh = generators.EmptyStreamGenerator((10000, 4, 2), sample_rate=1.*u.Hz, start_time=Time('2018-01-01'),
                                     frequency=frequency, sideband=sideband)
ph = functions.Power(fh, polarization=polarization)
ih = integration.Fold(ph, n_phase=100, phase=lambda t: t, step=4*u.s)
```

**Comment by mhvk** [comment]
@IMFardz - I think #62 should fix this. If the tests pass, I'll merge, so that you can try.
