### ISSUE TITLE
Using Scintillometry on numPy arrays

### ISSUE THREAD

**Issue by IMFardz** [mhvk/scintillometry#63]
More of an inquiry then an issue:

If I have a waterfall of frequency and time as a numpy array and a polyco file, would it be possible to use Scintillometry to obtain a folded numpy array? Currently, the Fold Class takes only takes in baseband stream readers.

**Comment by mhvk** [comment]
Not directly, but with some small trickery: use your file to generate a stream using `StreamGenerator`, using a function something like:
```
def my_source(sh):
    offset = sh.tell()
    return my_array[offset:offset+sh.samples_per_frame]

sh = StreamGenerator(my_source, shape=my_array.shape, start_time=..., sample_rate=...)
```
And then feed this stream into the `Fold` class.

Note that really what this is doing is associating metadata with your file that are needed for folding anyway.

p.s. If this works, it would be a very nice example for a small tutorial!

**Comment by IMFardz** [comment]
I think it works. Thanks!

**Comment by mhvk** [comment]
Great!  As mentioned, a short entry in the documentation might be very useful for others!
