### ISSUE TITLE
Make new phase utilities useful for integration

### ISSUE THREAD

**Issue by mhvk** [mhvk/scintillometry#71]
Right now the phase utilities output 2-part phases, with an integer and a fractional part. But the `phase` callable used for integration is expected to produce a single value.

Possible solutions: 
1. Have an option to output just a single value
2. Create a new `Phase` class similar to `Time` that holds the two values, and which can be subtracted, etc., giving a `DeltaPhase` (also two-part), but with the option to convert to a `Quantity` with units of cycle.

**Comment by luojing1211** [comment]
PINT has a phase class:
https://github.com/nanograv/PINT/blob/master/pint/phase.py. I think it has similar functionality. We can consider doing something like it.  But it looks like we are going to duplicate the code if PINT is not a required dependency.

**Comment by mhvk** [comment]
Hmm, the one I've been writing yesterday is more advanced, much more like `Time`, e.g., automatically becoming a `Quantity` when dividing by, say, a time span. Possibly we can experiment here and then transfer over to PINT!?  See 
https://github.com/mhvk/scintillometry/compare/phase-class?expand=1

Note that for the phase parts, I wouldn't mind depending on PINT, though it would need to be on pypi and it would help if it wouldn't auto-download giant files - as is, the tests run very slow because of it! (not sure why the caching doesn't work...).

**Comment by luojing1211** [comment]
That is indeed more advanced. The phase class in PINT handles phase wrap
(e.g., when the fractional phase is bigger than 0.5, it will be wrapped
to the negative fractional phase)
-Jing

**Comment by mhvk** [comment]
I'd like the `Phase` class to "do the right thing" when fed into ufuncs such as `np.cos`, but it turned out to be tricky to get this right with a new class. Basing myself on `Quantity` seems a bit easier. Attempt at
https://github.com/mhvk/scintillometry/pull/new/phase-as-specific-quantity

Here, I also tried to make it more compatible with PINT, having `.int` and `.frac` attributes.
