### ISSUE TITLE
Add sideband "0"

### ISSUE THREAD

**Issue by luojing1211** [mhvk/scintillometry#73]
In PSRFITS SUBINT HDUs, the frequency is labeled in the center of the frequency band. We can shift it to the upper or lower. But should we add something like 0 which indicates it is the center of the band?

**Comment by mhvk** [comment]
In our context, sideband really means how frequency is ordered within a band (i.e., if you take an FT, how to interpret the sub-channels: for real data, this means the first frequency in an FT will either be at the top or the bottom; for complex data, it means the first frequency is always in the middle, but the next one can either be above or below.

So, the +1 or -1 is always needed (and explicitly used: see https://github.com/mhvk/scintillometry/blob/master/scintillometry/channelize.py#L73)

I think we probably need to clarify the docstring; it is rather brief now: https://github.com/mhvk/scintillometry/blob/master/scintillometry/base.py#L69

Or better, add this to some overall outline of what the attributes and properties mean... Labelling this `docs` for that reason.

Of course, for PSRFITS, we need to be sure that we can convert, so we do need to keep the `sideband` information in there...
