### ISSUE TITLE
Integrating Multi-Channel Data with Corrupt Channel

### ISSUE THREAD

**Issue by IMFardz** [mhvk/scintillometry#75]
I am currently having a small problem which I think Scintillometry can not handle at the moment.

I have baseband data recorded as vdif, with 8 separate channels. I would like to use the scintillometry to create dynamic spectra and folds. However, the last channel is corrupted and is missing almost all of its data. The first seven channels are completely fine however and I would like to use the fold class on just these.

I will roughly illustrate the procedure I followed. 

First, I tried is using the GetItem class from scintillometry.shaping:
`fh = vdif.open(fdir + fname, 'rs')`
`gih = GetItem(fh, slice(0, 6))`

I then make an integration object like this:
`integrator = integration.Fold(gih, n_phase=1024, phase=psr_polyco, step=10*u.s, average=True)`

However, if I try something like
`integrator.read(count=1)`

I get an error message (attached) which says it cannot find all of the frames, likely because the eighth channel. I have also tried using different slices with no avail. My hope was that the GetItem class would allow me to now have to worry about the missing frames in the last channel, but it appears this is not the case.

Currently, I am planning on just separating the channels up into to separate files which may be a bit tedious. However, if there is an easier way to avoid this problem that would be amazing.

[error.txt](https://github.com/mhvk/scintillometry/files/2997365/error.txt)

**Comment by mhvk** [comment]
@IMFardz - yes, `GetItem` only takes a nice and complete stream and picks off bits; it does not tell the underlying reader not to bother with some channels.

But I think if you use the `subset` keyword for the vdif reader, it should work, i.e., `fh = vdif.open(fdir + fname, 'rs', subset=slice(0, 6))` - here, I am assuming your corrupted thread has ID=7. See https://baseband.readthedocs.io/en/stable/api/baseband.vdif.open.html#baseband.vdif.open

**Comment by mhvk** [comment]
p.s. If the above doesn't work, it would be a baseband issue...  It will not quite work for your other case, where odd and even were separate, as frames still have to be grouped together.

**Comment by IMFardz** [comment]
I think using the subset parameter when opening the baseband streamer worked. Thanks!
