### ISSUE TITLE
broadcast frequency 

### ISSUE THREAD

**Issue by luojing1211** [mhvk/scintillometry#76]
This is related to the PR #74. 
PSRFITs data shape organized as (nsample, nbin, nchan, npol). When I input the frequency as 1-d array, it fails at the broadcast check.  Since an (nchan, ) array can not broadcast to (nbin, nchan, npol). I need to reshape the frequency to (1, nchan, 1). Should I force frequency to (1, nchan, 1)?

**Comment by mhvk** [comment]
I'm not sure I understand fully, but perhaps #74 should include a [`Transpose`](https://scintillometry.readthedocs.io/en/latest/api/scintillometry.shaping.Transpose.html#scintillometry.shaping.Transpose)?

**Comment by luojing1211** [comment]
The problem is the input frequency will be checked in the base._check_shape(frequency) function, which makes sure the frequency can be broadcast to the input shape[1:]. However, an 1-d array has a shape (ncha,) can not be broadcasted to (1, nchan, 1). Maybe Transpose is the way to go.
