### ISSUE TITLE
Allow array of frequencies for phases.PintPhase 

### ISSUE THREAD

**Issue by quantumfx** [mhvk/scintillometry#95]
I have a waterfall from a PSRFITS file of shape (frequencies, phase) and wish to compute the new phases for each frequency from a .par file. Using an array of frequencies currently throws a `ValueError`.

> `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

**Comment by mhvk** [comment]
@luojing1211 - does `PINT` broadcast frequency?

@quantumfx - could you tell exactly how you input it? I ask since `PintPhase` takes times, not phases, and the shapes matter. Maybe easiest would be if you can give a minimal example with just 3 TOAs and 2 frequencies - that can become our test case!

**Comment by luojing1211** [comment]
I don't think it does right now. But I can fix it.
-Jing

**Comment by quantumfx** [comment]
```
phase = phases.PintPhase('timing/11y/NANOGrav_11y/par/J1713+0747_NANOGrav_11yv1.gls.par','GB',1.4*u.GHz)
``` 
followed by 
```
t0 = 53798*u.day + 8*u.h + 12*u.minute + 53*u.second + np.float128(0.488318431293770)*u.second
t0 = Time(t0,format='mjd')
phase(t0)
```
works, but 
```
phase = phases.PintPhase('timing/11y/NANOGrav_11y/par/J1713+0747_NANOGrav_11yv1.gls.par','GB',np.array([1.4,1.5])*u.GHz)
```
followed by the same command doesn't

Here's the par file: [J1713+0747_NANOGrav_11yv1.gls.par.zip](https://github.com/mhvk/scintillometry/files/3272318/J1713%2B0747_NANOGrav_11yv1.gls.par.zip)

**Comment by luojing1211** [comment]
No, it does not. I think the best solution is to use a for loop to create
the phase for each TOAs.
-Jing

**Comment by mhvk** [comment]
See #98 for a fix. @quantumfx - even with the fix, you have to ensure that the frequencies either have exactly the same shape as the times, or can be broadcast.

This is the case in your example, where you get two TOAs for the same scalar time. If you were to pass in two times, you would get two TOAs, one with time1,freq1 and one with time2,freq2. If you wanted TOAs for each time and freq, you'd pass in `np.array([[1.4], [1.5]])*u.GHz`.

**Comment by luojing1211** [comment]
I am not sure if this going to work for the case below:
```
>>> pt = PintToas('ARO', np.array([[1.4], [1.5]])*u.GHz)
>>> times1 = Time(np.arange(100) + 55000.0, format='mjd') # TOAs at 1.4 GHz
>>> times2 = Time(np.arange(30) + 55001.0, format='mjd') # TOAs at 1.5 GHz
>>> TOAs = pt(Time[times1, times2]) 
```

**Comment by mhvk** [comment]
`Time([times1, times2])` gives you a new time with shape `(130,)`; you'd get phases at both frequencies for all , i.e., the output shape will be `(2, 130)`. 

I agree that this is not necessarily all that useful this way. But it is useful if you have a list of frequencies that is the same length as the times.

**Comment by luojing1211** [comment]
For @quantumfx usage. He may face the same problem with different observatories, which makes me like my .tim file idea.
