### ISSUE TITLE
PINT and Polyco inconsistent in test

### ISSUE THREAD

**Issue by mhvk** [mhvk/scintillometry#97]
@luojing1211 - it turns out we were not actually testing the PINT phases at all - see #96, where I turned it on again. But the tests reveal that the polyco and PINT are actually inconsistent. My guess is that it is the polyco file that is the problem (my `Predictor` routine returns phases consistent with it), but I'm not sure. Could you have a look? Obviously, we should fix this...

See https://github.com/mhvk/scintillometry/blob/master/scintillometry/tests/test_phases.py#L84

**Comment by luojing1211** [comment]
Maybe PINT uses a different reference phase calcualtion. I will double check it.

**Comment by mhvk** [comment]
@luojing1211 - maybe the first thing to check is that the `.par` file is OK. I remember editing it, removing pieces that seemed just too long and irrelevant for the tests, but perhaps I made a mistake...

**Comment by luojing1211** [comment]
@mhvk, The constant offset makes sense. Polyco is generated by Tempo2. PINT AND tempo2 do have a constant offset since this two software treat the reference time or phase differently.

**Comment by mhvk** [comment]
OK, great to know this is not an issue. Could you document it? (Maybe just in `phases.rst`) And rewrite the comment?

**Comment by mhvk** [comment]
fixed by #109
